spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:8080/eureka/
girl:
  age: 18
  name: liqun

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka-test.com:8080/eureka/
     
girl:
  age: 17
  name: liqun
